import pytest

# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import immutable_list as immutable_list_module

def test_empty_immutable_list_basic_operations():
    """
    Test basic operations on an empty ImmutableList instance.
    """
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()

    # Verify equality with itself
    is_equal_to_itself = empty_list.__eq__(empty_list)

    # Get string representation
    string_repr = empty_list.__str__()

    # Convert to regular Python list
    regular_list = empty_list.to_list()

    # Concatenate the regular list with itself
    concatenated_list = regular_list.__add__(regular_list)

    # Get length of the regular list
    regular_list_length = regular_list.__len__()

    # Attempt to add regular list to immutable list (discard result)
    empty_list.__add__(regular_list)

def test_empty_immutable_list_edge_case_operations():
    """Test edge case operations on an empty ImmutableList instance."""
    
    true_value = True
    
    # Create an empty ImmutableList
    empty_list = immutable_list_module.ImmutableList()
    
    # Test equality comparison with a non-list value
    equality_result = empty_list.__eq__(true_value)
    
    # Concatenate empty list with itself
    concatenated_list = empty_list.__add__(empty_list)
    
    # Try to find the equality result in the empty list
    find_result = empty_list.find(equality_result)
    
    # Get string representation
    string_representation = empty_list.__str__()
    
    # Unshift the empty list with itself
    unshifted_list = empty_list.unshift(empty_list)
    
    # Reduce using the list itself as the reducing function
    # This is unusual but preserved from original test
    unshifted_list.reduce(unshifted_list, true_value)

def test_find_self_in_immutable_list_with_contradictory_empty_flag():
    """Test that ImmutableList operations don't crash when is_empty=True but head has value."""
    true_value = True
    
    # Create list with contradictory state: is_empty=True but head has value
    original_list = immutable_list_module.ImmutableList(true_value, is_empty=true_value)
    
    # Append same value to the list
    appended_list = original_list.append(true_value)
    
    # Try to find the list within itself (unusual but should not crash)
    original_list.find(original_list)

def test_add_none_to_empty_immutable_list():
    """
    Test that the __add__ method can be called with None argument
    on an empty immutable list without raising an error.
    """
    empty_list = immutable_list_module.ImmutableList()
    none_argument = None
    
    # Call __add__ with None to verify it doesn't crash
    empty_list.__add__(none_argument)

def test_find_on_nested_immutable_list_with_non_boolean_is_empty():
    """
    Test the find method on an ImmutableList constructed with another
    ImmutableList as head and a non-boolean is_empty parameter.
    """
    empty_list = immutable_list_module.ImmutableList()
    length_of_empty = empty_list.__len__()  # This value is unused, but we call the method.
    nested_list = immutable_list_module.ImmutableList(
        empty_list, is_empty=empty_list
    )
    nested_list.find(nested_list)

def test_immutable_list_with_false_head_calls_len_and_find():
    """Test ImmutableList with False head value can call __len__ and find methods."""
    is_empty_flag = False
    immutable_list = immutable_list_module.ImmutableList(is_empty_flag, is_empty=is_empty_flag)
    
    # Get string representation of length
    length_string = immutable_list.__len__()
    
    # Attempt to find the list within itself (self-referential test)
    immutable_list.find(immutable_list)

def test_find_converted_list_value():
    """
    Test that find method can search for a value that was converted 
    from the ImmutableList to a regular list.
    """
    is_empty_flag = False
    # Create an ImmutableList with False as head and is_empty=False
    immutable_list = immutable_list_module.ImmutableList(
        is_empty_flag, 
        is_empty=is_empty_flag
    )
    converted_list = immutable_list.to_list()
    # Search for the converted list value in the original immutable list
    immutable_list.find(converted_list)

def test_find_none_on_empty_list_then_append_self_and_add_none():
    """
    Test find operation with None on empty immutable list, then append self and convert to regular list.
    """
    # Create empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Try to find None in the empty list
    none_value = None
    found_result = empty_list.find(none_value)
    
    # Append the empty list to itself (creates list containing itself)
    appended_list = empty_list.append(empty_list)
    
    # Convert to regular Python list
    regular_list = appended_list.to_list()
    
    # Call __add__ method with None (typically concatenates lists)
    regular_list.__add__(none_value)

def test_non_empty_immutable_list_map_with_list_from_another_instance():
    """
    Test mapping on a non-empty ImmutableList using a list from another instance.
    """
    is_empty_flag = False
    non_empty_list = immutable_list_module.ImmutableList(is_empty=is_empty_flag)
    list_from_non_empty = non_empty_list.to_list()
    
    empty_list = immutable_list_module.ImmutableList()
    list_from_non_empty_again = non_empty_list.to_list()
    
    # Map the non-empty list using the list from another instance
    # Note: This may test error handling or specific behavior of map()
    non_empty_list.map(list_from_non_empty_again)

def test_immutable_list_operations_with_none_values():
    """Test ImmutableList operations with None values including unshift, append, and map."""
    
    # Create an ImmutableList with None as both head and tail
    none_value = None
    empty_list = immutable_list_module.ImmutableList(none_value, none_value)
    
    # Unshift None onto the empty list
    list_with_none_unshifted = empty_list.unshift(none_value)
    
    # Unshift the resulting list onto the original empty list
    # Note: This result is not used further in the test
    list_with_list_unshifted = empty_list.unshift(list_with_none_unshifted)
    
    # Append None to the list that had None unshifted onto it
    appended_list = list_with_none_unshifted.append(none_value)
    
    # Map over the appended list with a None function
    # This tests that map can handle None as a function argument
    appended_list.map(none_value)

def test_filter_with_same_list_instance():
    """Test that filter method can be called with the same list instance as argument."""
    is_empty_flag = False
    # Create a non-empty list with False as head element
    list_instance = immutable_list_module.ImmutableList(is_empty_flag, is_empty=is_empty_flag)
    # Call filter with the same list instance (unusual but valid for testing)
    list_instance.filter(list_instance)

def test_filter_on_concatenated_empty_list():
    """
    Test filtering a concatenated empty immutable list using its length as predicate.
    """
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Concatenate the empty list with itself
    concatenated_list = empty_list.__add__(empty_list)
    
    # Get the length of the concatenated list
    list_length = concatenated_list.__len__()
    
    # Filter the concatenated list using its length as predicate
    concatenated_list.filter(list_length)

def test_find_on_immutable_list_with_none_nodes_returns_element_with_length():
    """Test that calling find on an ImmutableList constructed with None nodes
    returns an element that supports __len__."""
    
    # Create a search value
    search_value = 1947
    
    # Create None node for constructing the list
    none_node = None
    
    # Create an ImmutableList with None as both head and tail
    immutable_list = immutable_list_module.ImmutableList(none_node, none_node)
    
    # Find the search value in the list
    found_element = immutable_list.find(search_value)
    
    # Verify the found element has a __len__ method
    found_element.__len__()

def test_find_with_self_reference():
    """
    Test that find() can be called with the list itself as the search argument.
    """
    # Create a non-empty list with False as the head element
    is_empty_flag = False
    list_instance = immutable_list_module.ImmutableList(is_empty_flag, is_empty=is_empty_flag)
    
    # Attempt to find the list within itself
    list_instance.find(list_instance)

def test_immutable_list_reduce_and_find_with_false_and_empty_list():
    """
    Test reduce and find operations on ImmutableList with False values and empty list.
    """
    false_value = False
    
    # Create empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Reduce empty list using False as the reducing function and empty list as initial value
    reduced_value = empty_list.reduce(false_value, empty_list)
    
    # Create non-empty list with False as head and is_empty=False
    list_with_false_head = immutable_list_module.ImmutableList(false_value, is_empty=false_value)
    
    # Attempt to find the list within itself
    list_with_false_head.find(list_with_false_head)

def test_immutable_list_default_constructor() -> None:
    """Test that an empty ImmutableList can be instantiated."""
    empty_immutable_list = immutable_list_module.ImmutableList()

def test_immutable_list_str_and_find_with_false():
    """Test ImmutableList string representation and find method with False head and is_empty=False."""
    false_flag = False
    
    # Create an ImmutableList with False as head and is_empty=False
    immutable_list = immutable_list_module.ImmutableList(false_flag, is_empty=false_flag)
    
    # Get string representation
    string_representation = immutable_list.__str__()
    
    # Call find method with the list itself as argument
    immutable_list.find(immutable_list)

def test_immutable_list_unshift_and_find_self():
    """
    Test that an ImmutableList can unshift itself and then find itself.
    """
    # Create a non-empty ImmutableList with False as the head value
    false_value = False
    original_list = immutable_list_module.ImmutableList(false_value, is_empty=false_value)
    
    # Create a new list by unshifting the original list onto itself
    new_list = original_list.unshift(original_list)
    
    # Attempt to find the original list within itself
    # This tests the find method's behavior when searching for the list itself
    original_list.find(original_list)

def test_find_false_in_immutable_list_after_unshift_and_append():
    """
    Test that find() can locate False in an ImmutableList after unshift and append operations.
    """
    false_value = False
    
    # Create a non-empty immutable list
    original_list = immutable_list_module.ImmutableList(is_empty=false_value)
    
    # Add false_value to the front via unshift
    list_after_unshift = original_list.unshift(false_value)
    
    # Append the original list to create a nested structure
    list_after_append = list_after_unshift.append(original_list)
    
    # Attempt to find false_value in the final list
    list_after_append.find(false_value)

def test_immutable_list_operations_with_contradictory_is_empty():
    """Test ImmutableList operations when created with contradictory is_empty=True."""
    true_value = True
    
    # Create list with contradictory state: contains element but is_empty=True
    original_list = immutable_list_module.ImmutableList(true_value, is_empty=true_value)
    
    # Append another element to create new list
    appended_list = original_list.append(true_value)
    
    # Get length of the new list
    appended_list_length = appended_list.__len__()
    
    # Attempt to find original_list within itself
    original_list.find(original_list)

def test_immutable_list_operations_with_self_reference():
    """Test various ImmutableList operations with self-referential structures."""
    
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Append the empty list to itself (creating a self-referential structure)
    list_with_self = empty_list.append(empty_list)
    
    # Reduce the empty list using list_with_self as both function and initial value
    reduced_result = empty_list.reduce(list_with_self, list_with_self)
    
    # Check equality between list_with_self and empty_list
    are_equal = list_with_self.__eq__(empty_list)
    
    # Unshift list_with_self onto itself
    unshifted_list = list_with_self.unshift(list_with_self)
    
    # Get string representation of unshifted_list
    string_representation = unshifted_list.__str__()
    
    # Create a new list with string_representation as the is_empty parameter
    list_with_string_param = immutable_list_module.ImmutableList(is_empty=string_representation)
    
    # Append reduced_result to itself
    appended_reduced_result = reduced_result.append(reduced_result)
    
    # Find reduced_result within unshifted_list
    unshifted_list.find(reduced_result)

def test_immutable_list_operations_with_nested_lists():
    """Test various operations on ImmutableList with nested lists."""
    
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Create a list with the empty list as its head element
    list_with_empty_list_as_head = empty_list.unshift(empty_list)
    
    # Reduce the empty list using the nested list as both function and initial value
    reduced_result = empty_list.reduce(list_with_empty_list_as_head, list_with_empty_list_as_head)
    
    # Get the length of the list with empty list as head
    length_of_list_with_empty_list_as_head = list_with_empty_list_as_head.__len__()
    
    # Create a list with the nested list as its head element
    list_with_nested_list_as_head = list_with_empty_list_as_head.unshift(list_with_empty_list_as_head)
    
    # Check if the deeply nested list equals the original empty list
    are_nested_and_empty_lists_equal = list_with_nested_list_as_head.__eq__(empty_list)
    
    # Create a new list with the length value as the is_empty flag
    new_list_with_length_flag = immutable_list_module.ImmutableList(is_empty=length_of_list_with_empty_list_as_head)
    
    # Call find on the reduced result with itself as the argument
    reduced_result.find(reduced_result)

def test_reduce_on_immutable_list_with_contradictory_is_empty_flag():
    """Test reduce method on ImmutableList initialized with contradictory is_empty flag."""
    
    true_value = True
    empty_dict = {}
    
    # Create an ImmutableList with dictionary as tail
    list_with_dict_tail = immutable_list_module.ImmutableList(tail=empty_dict)
    
    # Create an ImmutableList with contradictory parameters: 
    # has a head value but also marked as empty
    list_with_true_head_and_empty_flag = immutable_list_module.ImmutableList(
        true_value, 
        is_empty=true_value
    )
    
    # Convert the contradictory list to a regular list
    converted_list = list_with_true_head_and_empty_flag.to_list()
    
    # Attempt to reduce the list using itself as both function and initial value
    list_with_true_head_and_empty_flag.reduce(converted_list, converted_list)

