import pytest

# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import immutable_list as immutable_list_module

def test_empty_immutable_list_basic_operations():
    """Test basic operations on an empty ImmutableList."""
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Test equality with itself
    is_equal_to_itself = empty_list.__eq__(empty_list)
    
    # Get string representation
    string_representation = empty_list.__str__()
    
    # Convert to regular list
    regular_list = empty_list.to_list()
    
    # Concatenate the regular list with itself
    concatenated_list = regular_list.__add__(regular_list)
    
    # Get length of the regular list
    list_length = regular_list.__len__()
    
    # Attempt to add regular list to the immutable list
    empty_list.__add__(regular_list)

def test_empty_immutable_list_operations_without_assertions():
    """
    Test various operations on an empty ImmutableList.
    Exercises equality, concatenation, element finding, string conversion,
    unshift, and reduce methods without assertions.
    """
    true_value = True

    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()

    # Compare list with a boolean (should return False)
    is_equal = empty_list.__eq__(true_value)

    # Concatenate the empty list with itself
    concatenated_list = empty_list.__add__(empty_list)

    # Attempt to find the equality result in the empty list
    found_item = empty_list.find(is_equal)

    # Get string representation of the empty list
    string_representation = empty_list.__str__()

    # Create a new list by prepending the empty list to itself
    unshifted_list = empty_list.unshift(empty_list)

    # Reduce the unshifted list using itself as initial value and True as accumulator
    unshifted_list.reduce(unshifted_list, true_value)

def test_find_self_in_immutable_list_with_contradictory_is_empty():
    """
    Test finding a list within itself when created with contradictory is_empty flag.
    """
    # Create a value to use as list element
    test_value = True
    
    # Create list with contradictory state: has element but is_empty=True
    original_list = immutable_list_module.ImmutableList(test_value, is_empty=test_value)
    
    # Append same value to create new list
    appended_list = original_list.append(test_value)
    
    # Attempt to find the original list within itself
    original_list.find(original_list)

def test_immutable_list_add_none_to_empty_list():
    """Test that adding None to an empty ImmutableList doesn't raise an exception."""
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Test that adding None doesn't raise an exception
    none_argument = None
    empty_list.__add__(none_argument)

def test_find_self_in_list_with_empty_head():
    """Test that find method works correctly when searching for a list within itself."""
    
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Get the length of the empty list (should be 0)
    empty_list_length = empty_list.__len__()
    
    # Create a list with the empty list as its head element
    # Note: is_empty parameter is set to the empty list instance (unusual but preserved)
    self_referential_list = immutable_list_module.ImmutableList(
        empty_list, is_empty=empty_list
    )
    
    # Try to find the list within itself
    self_referential_list.find(self_referential_list)

def test_immutable_list_length_and_find_self():
    """Test that ImmutableList can compute its length and attempt to find itself within itself."""
    is_empty_flag = False
    immutable_list = immutable_list_module.ImmutableList(is_empty_flag, is_empty=is_empty_flag)
    
    # Get the length of the list (should be 1 since it contains one element)
    list_length = immutable_list.__len__()
    
    # Attempt to find the list within itself (edge case testing)
    immutable_list.find(immutable_list)

def test_find_with_list_converted_from_immutable_list():
    """
    Test that find can be called with the list representation of the same immutable list.
    """
    false_flag = False
    # Create a non-empty immutable list with False as the head element
    immutable_list = immutable_list_module.ImmutableList(false_flag, is_empty=false_flag)
    # Convert the immutable list to a regular list
    converted_list = immutable_list.to_list()
    # Attempt to find the converted list within the immutable list
    immutable_list.find(converted_list)

def test_empty_list_find_none_append_self_and_call_add_on_result():
    """Test operations on empty immutable list: find None, append self, convert to list, then call __add__ with None."""
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Attempt to find None in the empty list (should return None)
    found_value = empty_list.find(None)
    
    # Append the empty list to itself, creating a list containing itself
    list_with_empty = empty_list.append(empty_list)
    
    # Convert the immutable list to a regular Python list
    regular_list = list_with_empty.to_list()
    
    # Call __add__ method on the regular list with None as argument
    # Note: This tests that the operation doesn't raise exceptions
    regular_list.__add__(None)

def test_map_with_non_empty_list_converted_to_list():
    """Test that map can be called with a list converted from a non-empty ImmutableList."""
    is_empty_flag = False
    non_empty_list = immutable_list_module.ImmutableList(is_empty=is_empty_flag)
    converted_list = non_empty_list.to_list()
    
    empty_list = immutable_list_module.ImmutableList()
    same_converted_list = non_empty_list.to_list()
    
    # Call map with the list (unusual, but preserving original behavior)
    non_empty_list.map(same_converted_list)

def test_immutable_list_operations_with_none():
    """Test various ImmutableList operations with None values."""
    none_value = None
    
    # Create an empty ImmutableList (head=None, tail=None)
    empty_list = immutable_list_module.ImmutableList(none_value, none_value)
    
    # Unshift None onto the empty list
    list_with_none_unshifted = empty_list.unshift(none_value)
    
    # Unshift the previous list onto the empty list (result unused)
    list_with_list_unshifted = empty_list.unshift(list_with_none_unshifted)
    
    # Append None to the list with None unshifted
    appended_list = list_with_none_unshifted.append(none_value)
    
    # Map with None as the function (should handle gracefully)
    appended_list.map(none_value)

def test_filter_on_non_empty_list_with_false_head_and_self_as_argument():
    """Test filter method on non-empty ImmutableList with False head value using itself as filter argument."""
    false_value = False
    non_empty_list_with_false_head = immutable_list_module.ImmutableList(
        false_value, is_empty=false_value
    )
    # Call filter with the list itself as argument (unusual but valid)
    non_empty_list_with_false_head.filter(non_empty_list_with_false_head)

def test_filter_with_length_of_concatenated_list():
    """
    Test that filter can be called with the length of a list concatenated with itself.
    """
    empty_list = immutable_list_module.ImmutableList()
    concatenated_list = empty_list.__add__(empty_list)
    concatenated_length = concatenated_list.__len__()
    
    # Note: This test calls filter with an integer argument rather than a predicate
    # Preserving original behavior which may test error handling
    concatenated_list.filter(concatenated_length)

def test_find_on_empty_list_returns_object_with_len_method():
    """Test that find() on an empty ImmutableList returns an object with __len__ method."""
    search_value = 1947
    none_value = None
    
    # Create empty ImmutableList (head=None, tail=None)
    empty_list = immutable_list_module.ImmutableList(none_value, none_value)
    
    # Search for value in empty list
    find_result = empty_list.find(search_value)
    
    # Verify result has __len__ method (test passes if no AttributeError)
    find_result.__len__()

def test_find_self_in_non_empty_list_with_false_element():
    """
    Test that searching for the list itself within a non-empty list
    (where the list contains False as its element) executes without error.
    """
    # Create a non-empty list with False as its element
    false_element = False
    non_empty_list = immutable_list_module.ImmutableList(
        head=false_element, 
        is_empty=false_element  # False indicates list is not empty
    )
    
    # Attempt to find the list within itself
    # This tests the find method's behavior when searching for the container
    non_empty_list.find(non_empty_list)

def test_immutable_list_reduce_with_false_and_find_on_self():
    """
    Test ImmutableList.reduce() with False as initial value and the list itself as reducer,
    followed by find() operation on a non-empty list.
    """
    false_flag = False
    
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Reduce the empty list using False as initial value and the list itself as reducer
    reduction_result = empty_list.reduce(false_flag, empty_list)
    
    # Create a non-empty list with False as head and is_empty=False
    non_empty_list = immutable_list_module.ImmutableList(false_flag, is_empty=false_flag)
    
    # Attempt to find the list within itself
    non_empty_list.find(non_empty_list)

def test_create_empty_immutable_list():
    """Test that an empty ImmutableList can be instantiated."""
    empty_list = immutable_list_module.ImmutableList()  # Default constructor creates empty list

def test_find_self_in_non_empty_list_with_false_head():
    """
    Test that find method can be called with the list itself as argument
    on a non-empty list with False head.
    """
    is_empty_flag = False
    immutable_list = immutable_list_module.ImmutableList(is_empty_flag, is_empty=is_empty_flag)
    string_representation = immutable_list.__str__()
    # Attempt to find the list within itself (edge case)
    immutable_list.find(immutable_list)

def test_immutable_list_self_referential_unshift_and_find():
    """Test unshifting an ImmutableList onto itself and then finding itself within the list."""
    # Create an ImmutableList with False as head and is_empty=False
    is_empty_flag = False
    initial_list = immutable_list_module.ImmutableList(is_empty_flag, is_empty=is_empty_flag)
    
    # Unshift the list onto itself
    unshifted_list = initial_list.unshift(initial_list)
    
    # Try to find the list within itself
    initial_list.find(initial_list)

def test_find_on_immutable_list_after_unshift_and_append():
    """Test that find() works on an ImmutableList after unshift and append operations."""
    false_value = False
    
    # Create a non-empty ImmutableList
    base_list = immutable_list_module.ImmutableList(is_empty=false_value)
    
    # Add false_value to the front via unshift
    list_after_unshift = base_list.unshift(false_value)
    
    # Append the original list to create a nested structure
    list_after_append = list_after_unshift.append(base_list)
    
    # Verify find() can locate the false_value in the modified list
    list_after_append.find(false_value)

def test_append_to_immutable_list_and_find():
    """Test creating an immutable list with is_empty flag, appending an element,
    getting its length, and attempting to find the list within itself."""
    
    # Create a boolean value to use as list element
    true_value = True
    
    # Create an immutable list marked as empty but with an element
    # Note: This creates a semantically confusing state where is_empty=True
    # but an element is provided
    original_list = immutable_list_module.ImmutableList(true_value, is_empty=true_value)
    
    # Append the same boolean value to create a new list
    appended_list = original_list.append(true_value)
    
    # Get the length of the new list
    length_of_appended_list = appended_list.__len__()
    
    # Attempt to find the original list within itself
    # This is semantically unusual but tests the find() method
    original_list.find(original_list)

def test_immutable_list_complex_self_referential_operations():
    """
    Test complex self-referential operations on ImmutableList including reduce, unshift, and find.
    """
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Append the empty list to itself (self-referential structure)
    list_with_self = empty_list.append(empty_list)
    
    # Reduce the empty list using list_with_self as both function and initial value
    reduced_result = empty_list.reduce(list_with_self, list_with_self)
    
    # Check equality between list_with_self and empty_list (result unused)
    equality_check = list_with_self.__eq__(empty_list)
    
    # Unshift list_with_self onto itself
    unshifted_list = list_with_self.unshift(list_with_self)
    
    # Get string representation of the unshifted list
    string_representation = unshifted_list.__str__()
    
    # Create a new list with string_representation as is_empty parameter
    list_with_string_param = immutable_list_module.ImmutableList(is_empty=string_representation)
    
    # Append reduced_result to itself
    appended_reduced_result = reduced_result.append(reduced_result)
    
    # Find reduced_result within unshifted_list
    unshifted_list.find(reduced_result)

def test_immutable_list_operations_with_nested_lists_and_reduce():
    """Test ImmutableList operations including unshift, reduce, length, equality, 
    and find with nested list structures."""
    
    # Create an empty immutable list
    empty_list = immutable_list_module.ImmutableList()
    
    # Unshift the empty list onto itself (creating a nested structure)
    list_with_empty = empty_list.unshift(empty_list)
    
    # Reduce the empty list using list_with_empty as both function and initial value
    reduced_value = empty_list.reduce(list_with_empty, list_with_empty)
    
    # Get length of the list containing the empty list
    list_length = list_with_empty.__len__()
    
    # Unshift list_with_empty onto itself (further nesting)
    list_with_itself = list_with_empty.unshift(list_with_empty)
    
    # Check equality between the doubly-nested list and the original empty list
    are_equal = list_with_itself.__eq__(empty_list)
    
    # Create a new list with is_empty flag set to the length we computed
    list_with_length_flag = immutable_list_module.ImmutableList(is_empty=list_length)
    
    # Attempt to find reduced_value within itself
    reduced_value.find(reduced_value)

def test_reduce_with_list_as_function_and_initial_value():
    """Test ImmutableList.reduce() using a list as both function and initial value."""
    true_value = True
    empty_dict = {}
    
    # Create two different ImmutableList instances
    list_with_dict_tail = immutable_list_module.ImmutableList(tail=empty_dict)
    list_with_true_and_empty = immutable_list_module.ImmutableList(
        true_value, is_empty=true_value
    )
    
    # Convert the second list to a regular list
    converted_list = list_with_true_and_empty.to_list()
    
    # Call reduce with the list as both the function and initial value
    # This tests the reduce method's handling of unusual input patterns
    list_with_true_and_empty.reduce(converted_list, converted_list)

