import pytest

# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import python as python_module

def test_pyinfo_instantiation():
    """Test that PyInfo can be instantiated without errors."""
    py_info_instance = python_module.PyInfo()

