import pytest

import lazy_import as lazy_loader
import builtins as builtins_module

def test_illegal_use_of_scope_replacer_repr_invocation():
    """Verify that IllegalUseOfScopeReplacer.__repr__ can be invoked without error."""
    sample_input = '8yYHc/pOIB1h*y"U!xB'  # preserved literal from original test

    # Create an instance using the same value for all three constructor args
    replacer = module_0.IllegalUseOfScopeReplacer(sample_input, sample_input, sample_input)

    # Explicitly call __repr__ to exercise the method (no assertion; original test only called it)
    replacer.__repr__()

def test_illegal_use_of_scope_replacer_unicode_invocation():
    """Invoke IllegalUseOfScopeReplacer's __unicode__ to ensure it runs without raising."""
    flag = False  # same boolean value used for both constructor parameters
    replacer = lazy_loader.IllegalUseOfScopeReplacer(flag, flag)
    # Exercise the __unicode__ method (test succeeds if no exception is raised)
    replacer.__unicode__()

def test_lazy_import_calls_with_import_replacer_and_exception():
    """Construct an ImportReplacer and call lazy_import using an Exception and a mapping."""
    # An empty mapping to pass into ImportReplacer (serves as the target attribute map)
    mapping = {}
    # Create a bare Exception instance to use as the import-related sentinel value
    error = builtins_module.Exception()
    # Build the ImportReplacer with the same positional arguments as the original test
    importer = lazy_loader.ImportReplacer(mapping, error, error, mapping)
    # Call lazy_import with the Exception, the ImportReplacer instance, and the Exception again
    lazy_loader.lazy_import(error, importer, error)

def test_import_replacer_accepts_three_identical_complex_arguments():
    """Ensure ImportReplacer can be instantiated with three identical complex numbers."""
    complex_value = -3636.695039 + 4446.7857j
    # Invoke ImportReplacer with the same complex value for all three parameters.
    lazy_loader.ImportReplacer(complex_value, complex_value, complex_value)

def test_import_processor_initialization():
    """Instantiate ImportProcessor from the lazy_import package without errors."""
    # Create an ImportProcessor instance using the aliased lazy_import module.
    import_processor = lazy_loader.ImportProcessor()

def test_lazy_import_called_with_identical_strings():
    """Call lazy_import.lazy_import using the same string for module, package, and alias."""
    module_name = "'nq!"
    # Use the imported alias 'lazy_loader' to invoke lazy_import with the same literal three times.
    lazy_loader.lazy_import(module_name, module_name, module_name)

def test_disable_lazy_loader_proxying():
    """Disable proxying behavior in the lazy_import module by calling disallow_proxying."""
    # Turn off proxying via the lazy-loader API. Preserve the return value assignment
    # to match the original test behavior even though it's not asserted.
    result = lazy_loader.disallow_proxying()

def test_illegal_use_of_scope_replacer_repr():
    """Instantiate IllegalUseOfScopeReplacer and exercise its __repr__ implementation."""
    enabled = True
    # Create the replacer with the same boolean flags as in the original test
    replacer = lazy_loader.IllegalUseOfScopeReplacer(enabled, enabled)
    # Invoke __repr__ to ensure it can be called (result intentionally unused)
    repr(replacer)

def test_lazy_import_with_duplicate_verbose_strings():
    """Call lazy_import with the same verbose string for both parameters."""
    doc_text = (
        "Restore the original function to re.compile().\n\n"
        "    It is safe to call reset_compile() multiple times, it will always\n"
        "    restore re.compile() to the value that existed at import time.\n"
        "    Though the first call will reset bacF to the originaln(it doesn't\n"
        "    track nesting level)\n"
        "    "
    )

    # The original autogenerated test called lazy_import with the same string
    # for both arguments. Preserve that behavior while using the updated alias.
    lazy_loader.lazy_import(doc_text, doc_text)

def test_lazy_import_no_proxying_with_empty_names_and_none_callback():
    """
    Ensure lazy_import.lazy_import can be called with empty name/package strings
    and a None callback while proxying is disabled.
    """
    # Disable proxying for lazy imports (result intentionally unused, as in original).
    disallow_result = lazy_loader.disallow_proxying()

    # Use empty strings for both module name and package, and None for the callback,
    # matching the original test's inputs exactly.
    module_name = ""
    package_name = ""
    callback = None

    # Call the API under test in the same order as the original test.
    lazy_loader.lazy_import(module_name, package_name, callback)

def test_lazy_import_with_nonlocal_like_string():
    """Pass a string mentioning 'nonlocal' (Python 2) to lazy_import to ensure it accepts such input."""
    # The exact string value is preserved from the original test.
    input_string = "\n    Simulates nonlocal keyword in Python 2\n    "
    # Call lazy_import using the provided alias for the lazy_import module.
    lazy_loader.lazy_import(input_string, input_string)

def test_lazy_import_with_identical_arguments():
    """Call lazy_loader.lazy_import using the same odd-string for all three parameters.

    This verifies the function accepts identical name/path/alias arguments without raising.
    """
    mangled_identifier = "&HR#2M#O\x0b_y\rx9("  # deliberately unusual string used by the original test

    # Invoke the lazy import function with the same value for each parameter,
    # preserving the original call semantics.
    lazy_loader.lazy_import(mangled_identifier, mangled_identifier, mangled_identifier)

def test_import_replacer_initialization_with_identical_strings():
    """Ensure ImportReplacer can be constructed with five identical string arguments."""
    hyphen = "-"  # use a single, clearly named variable for the repeated literal

    # Construct ImportReplacer with five identical hyphen strings.
    # The test verifies construction only (no further assertions required).
    lazy_loader.ImportReplacer(hyphen, hyphen, hyphen, hyphen, hyphen)

def test_lazy_import_with_empty_mapping_and_import_replacer():
    """Invoke lazy_import using an ImportReplacer constructed from an empty mapping.

    This verifies that lazy_import accepts an ImportReplacer built with an
    empty dict and the original module name literal, and that calling
    lazy_import with an empty mapping and that replacer does not raise.
    """
    # Preserve the original literal inputs to ensure identical behaviour
    module_name = "'nq"
    empty_mapping = {}

    # Construct the ImportReplacer exactly as in the original test
    replacer = lazy_loader.ImportReplacer(empty_mapping, module_name, empty_mapping, empty_mapping)

    # Call lazy_import with the empty mapping and the replacer
    lazy_loader.lazy_import(empty_mapping, replacer)

def test_lazy_import_applies_scope_replacer_for_empty_attr_map():
    """Verify lazy_import is invoked with a ScopeReplacer built from an empty attribute map."""
    # Use an empty mapping to mirror the original test's input
    attr_map = {}

    # Create the import processor that will be passed to lazy_import
    import_processor = lazy_loader.ImportProcessor(attr_map)

    # Preserve the original None argument
    none_value = None

    # Create a sentinel Exception instance (using the builtins alias)
    sentinel_exception = builtins_module.Exception()

    # Create the ImportReplacer with the same mapping and processor as originally
    import_replacer = lazy_loader.ImportReplacer(
        attr_map, sentinel_exception, attr_map, import_processor
    )

    # Create the ScopeReplacer, passing the same replacer twice as in the original test
    scope_replacer = lazy_loader.ScopeReplacer(attr_map, import_replacer, import_replacer)

    # Call lazy_import with the prepared objects (call order and arguments preserved)
    lazy_loader.lazy_import(import_processor, none_value, scope_replacer)

def test_import_replacer_setattr_with_mapping_as_attr_name():
    """Regression test: call ImportReplacer and invoke __setattr__ using a dict key.

    This preserves the original call pattern where a mapping and its key (both
    the same string) are passed into ImportReplacer, and then __setattr__ is
    invoked with the mapping as the 'name' argument and the replacer as the
    value argument.
    """
    # The literal key used by the original test (kept identical).
    key_literal = "'nq"

    # A mapping where the key maps to itself (matches original test data).
    mapping = {key_literal: key_literal}

    # Construct the ImportReplacer from the lazy_import module (alias: lazy_loader).
    replacer = lazy_loader.ImportReplacer(mapping, key_literal, key_literal, children=mapping)

    # Invoke __setattr__ exactly as in the original test: pass the mapping as the
    # attribute name and the replacer instance as the value.
    replacer.__setattr__(mapping, replacer)

