#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-570 -p alvis
#SBATCH --gpus-per-node=A100:4 # 
#SBATCH -t 0-05:00:00
#SBATCH -o jobs/out/llama-loop-session.log

model=mixtral
temperatures=(0.1 0.2 0.5 0.7)

#Queue
#session=job-sum_func-queue
#test_path="/cephyr/NOBACKUP/groups/llm-readability/readability/data/queue_example/test_queue_example.py"
#module_path="/cephyr/NOBACKUP/groups/llm-readability/readability/data/queue_example/queue_example.py"

#StringValidation
session=job-sum_func-stringVal
test_path="/cephyr/NOBACKUP/groups/llm-readability/readability/data/string_utils_validation/test_string_utils_validation.py"
module_path="/cephyr/NOBACKUP/groups/llm-readability/readability/data/string_utils_validation/validation.py"

#Httpie_sessions
#session=job-sum_func-httpie
#test_path="/cephyr/NOBACKUP/groups/llm-readability/readability/data/httpie_sessions/test_httpie_sessions.py"
#module_path="/cephyr/NOBACKUP/groups/llm-readability/readability/data/httpie_sessions/sessions.py /cephyr/NOBACKUP/groups/llm-readability/readability/data/httpie_sessions/dicts.py"


ml purge
for temperature in "${temperatures[@]}"; do
    echo "Running with temperature $temperature"
    # running test
    apptainer exec /cephyr/NOBACKUP/groups/llm-readability/setup/mixtral.sif python -m src.summarize_functions \
    -m $model -s $session -t $temperature -p $module_path -tp $test_path
    
    # PUSHING TO REPO
    
    # Define the path to the repository's root
    REPO_DIR="/cephyr/NOBACKUP/groups/llm-readability/readability"
    
    # Change to the repository directory
    cd $REPO_DIR
    
    # Check if the directory change was successful
    if [ $? -ne 0 ]; then
        echo "Failed to change directory to $REPO_DIR. Exiting script."
        exit 1
    fi
    
    # Pull the latest changes from the remote repository
    echo "Pulling the latest changes from the repository..."
    git pull origin main
    
    # Check if the pull was successful
    if [ $? -ne 0 ]; then
        echo "Failed to pull the latest changes. Exiting script."
        exit 1
    fi
    
    # Add changes only in the 'output' folder
    git add output/
    
    # Commit the changes
    COMMIT_MESSAGE=" From Loop Job: Update output folder after model: $model session: $session temp: $temperature "
    COMMIT_STATUS=$(git commit -m "$COMMIT_MESSAGE")
    
    # Check if the commit was successful
    if [[ $COMMIT_STATUS == *"nothing to commit"* ]]; then
        echo "No changes to commit for temperature $temperature."
    else
        echo "Changes committed. Pushing to repository..."
        # Push the changes
        git push origin main
         echo "Changes pushed successfully for temperature $temperature."
    fi
done