import pytest

# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming_timer as timer

def test_timer_error_can_be_instantiated() -> None:
    """Test that TimerError can be instantiated without raising exceptions."""
    timer_error = timer.TimerError()

def test_starting_already_running_timer_raises_error():
    """Test that starting a timer that is already running raises TimerError."""
    # Create a timer and start it via context manager
    timer_instance = timer.Timer()
    same_timer = timer_instance.__enter__()  # Starts the timer
    # Exit context manager (stops timer)
    _ = timer_instance.__exit__()
    # Start the timer again
    _ = same_timer.start()  # Timer is now running
    # Attempt to start the same timer again while running -> should raise TimerError
    with pytest.raises(timer.TimerError):
        timer_instance.start()

def test_timer_context_manager_explicit_enter_exit() -> None:
    """Test that Timer can be used as a context manager via explicit __enter__ and __exit__ calls."""
    # Create a Timer instance
    timer_instance = timer.Timer()
    
    # Enter the context manager (starts the timer)
    entered_timer = timer_instance.__enter__()
    
    # Exit the context manager (stops the timer)
    exit_result = timer_instance.__exit__()

def test_timer_exit_without_context() -> None:
    """Test that Timer.__exit__ can be called without entering a context manager."""
    timer = module_0.Timer()
    timer.__exit__()

def test_timer_start_with_none_logger_and_unrelated_operations() -> None:
    """Test Timer with logger=None can start, then unrelated operations occur."""
    # Create a Timer with no logger
    none_logger = None
    timer_instance = timer.Timer(logger=none_logger)
    
    # Start the timer (returns None)
    start_return = timer_instance.start()
    
    # Perform unrelated dictionary operations
    empty_dict = {}
    none_key = None
    # Set a key of None to the dictionary itself (returns None)
    setitem_return = empty_dict.__setitem__(none_key, empty_dict)
    
    # Attempt to call __enter__ on None (will raise AttributeError)
    setitem_return.__enter__()

def test_timer_context_manager_with_mixed_parameters() -> None:
    """Test Timer operations with context manager, equality checks, and various parameter combinations."""
    # Create initial timer and enter context
    timer_a = timer.Timer()
    timer_a_context = timer_a.__enter__()  # Starts timer_a
    
    # Various test values
    negative_number = -1092
    
    # Create FloatArg instances (test-specific objects)
    float_arg_a = timer.FloatArg()
    
    # Create timer with timer instance as initial_text (unusual but preserved)
    timer_b = timer.Timer(initial_text=timer_a_context)
    
    float_arg_b = timer.FloatArg()
    
    # Check equality between timer and integer (should return False)
    equality_result = timer_a.__eq__(negative_number)
    
    # Stop the context timer and get elapsed time
    elapsed_time = timer_a_context.stop()
    
    # Create timer with FloatArg as text and equality result as initial_text
    timer_c = timer.Timer(text=float_arg_a, initial_text=equality_result)
    
    # Get string representations
    timer_a_repr = timer_a.__repr__()
    timer_c_repr = timer_c.__repr__()
    
    # Start timer_c (returns None)
    start_result = timer_c.start()

def test_timer_context_manager_operations_with_custom_parameters() -> None:
    """Test Timer operations including context manager, repr, eq, stop, and start with custom parameters."""
    
    # Create a timer and enter context (starts timing)
    timer = timer.Timer()
    context_timer = timer.__enter__()
    
    # Create test values
    negative_number = -1092
    
    # Get string representation of timer
    timer_repr = context_timer.__repr__()
    
    # Create FloatArg instances (custom parameter objects)
    float_arg = timer.FloatArg()
    
    # Create timer with initial text from timer representation
    timer_with_initial_text = timer.Timer(initial_text=timer_repr)
    
    # Create another FloatArg instance
    another_float_arg = timer.FloatArg()
    
    # Check equality between timer and negative number (should return False)
    equality_result = timer.__eq__(negative_number)
    
    # Stop the context timer and get elapsed time
    elapsed_time = context_timer.stop()
    
    # Create timer with custom text and initial text parameters
    timer_with_text_and_initial_text = timer.Timer(text=float_arg, initial_text=timer_repr)
    
    # Get representations of timers
    timer_repr_again = timer.__repr__()
    timer3_repr = timer_with_text_and_initial_text.__repr__()
    
    # Start the timer with custom parameters
    timer_with_text_and_initial_text.start()

def test_timer_start_exit_with_unrelated_dict_operations_and_error():
    """Test Timer start/exit alongside unrelated dictionary operations and an AttributeError."""
    # Create a Timer with no logger
    logger_none = None
    timer_instance = timer.Timer(logger=logger_none)
    
    # Start the timer (returns None)
    start_result = timer_instance.start()
    
    # Perform unrelated dictionary operations
    empty_dict = {}
    none_key = None
    
    # Stop the timer via context manager exit (returns None)
    exit_result = timer_instance.__exit__()
    
    # Set a dictionary key to the dictionary itself (returns None)
    setitem_result = empty_dict.__setitem__(none_key, empty_dict)
    
    # Get string representation of None (the result of __setitem__)
    repr_result = setitem_result.__repr__()
    
    # This line attempts to call .start() on None, which will raise AttributeError
    # Preserved from original test to maintain identical behavior
    setitem_result.start()

def test_timer_start_with_timer_instances_as_parameters() -> None:
    """Test that Timer can be started when constructed with other Timer instances as parameters."""
    # Create and start a timer via context manager
    timer_a = timer.Timer()
    timer_a_entered = timer_a.__enter__()  # Starts timer_a, returns same instance
    
    # Call __eq__ to get a value (likely boolean) for logger parameter
    eq_result = timer_a.__eq__(timer_a)
    
    # Stop timer_a via context manager exit
    timer_a.__exit__()
    
    # Create timer_b with timer_a_entered as initial_text and eq_result as logger
    timer_b = timer.Timer(initial_text=timer_a_entered, logger=eq_result)
    
    # Create timer_c with timer_a_entered as name, timer_b as initial_text, eq_result as logger
    timer_c = timer.Timer(timer_a_entered, initial_text=timer_b, logger=eq_result)
    
    # Start timer_c - should not raise despite unusual parameters
    timer_c.start()

def test_timer_start_stop_enter_copy() -> None:
    """Test a sequence of timer operations: start, stop, enter (context manager), and copy."""
    # Create a timer with a name
    timer_name = "Timer started"
    timer = timer.Timer(timer_name)

    # Start and stop the timer explicitly
    timer.start()
    elapsed_time = timer.stop()

    # Use the timer as a context manager (starts timer)
    context_timer = timer.__enter__()

    # Attempt to copy the timer (method may not exist)
    timer.copy()

