import pytest

# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import decorators as decorators_module

def test_cached_property_get_with_none_and_self():
    """
    Test cached_property.__get__ method when called with None and self as arguments.
    """
    # Create a cached_property decorator with None as the function
    none_instance = None
    cached_property_decorator = decorators_module.cached_property(none_instance)
    
    # First call to __get__ with None as instance and the decorator itself as owner
    result = cached_property_decorator.__get__(none_instance, cached_property_decorator)
    
    # Second call to __get__ with the decorator as both instance and owner
    cached_property_decorator.__get__(cached_property_decorator, cached_property_decorator)

def test_cached_property_get_with_set_and_self_owner():
    """
    Test that cached_property.__get__ can be called with a set instance
    and the descriptor itself as the owner.
    """
    empty_set = set()
    cached_property_instance = decorators_module.cached_property(empty_set)
    
    # Call __get__ with the set as instance and the descriptor itself as owner
    # This tests the descriptor protocol with unusual but valid arguments
    cached_property_instance.__get__(empty_set, cached_property_instance)

def test_cached_property_with_empty_set():
    """Test that cached_property can be instantiated with an empty set."""
    empty_set = set()
    # Note: This test verifies instantiation without assertion
    cached_property_instance = decorators_module.cached_property(empty_set)

