# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import headers as headers_module

def test_headers_formatter_can_be_instantiated():
    """Test that HeadersFormatter can be instantiated without errors."""
    # Simply creating an instance should not raise any exceptions
    headers_module.HeadersFormatter()

