#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-570 -p alvis
#SBATCH --gpus-per-node=A40:1 #  
#SBATCH -t 0-01:00:00
#SBATCH -o jobs/out/test-mistral.log

# Define model variable
#model=mistral

# Set session name
session=testing-mistral

ml purge

for temperature in 0.1 0.2 0.5 0.7
do
    echo "Running job with temperature $temperature"

    # Running test
    apptainer exec /cephyr/NOBACKUP/groups/llm-readability/setup/mixtral.sif python -m src.session \
    -s $session -t $temperature
    #-m $model -s $session -t $temperature

    # Pushing to repo

    # Define the path to the repository's root
    REPO_DIR="/cephyr/NOBACKUP/groups/llm-readability/readability"

    # Change to the repository directory
    cd $REPO_DIR

    # Check if the directory change was successful
    if [ $? -ne 0 ]; then
        echo "Failed to change directory to $REPO_DIR. Exiting script."
        exit 1
    fi

    # Pull the latest changes from the remote repository
    echo "Pulling the latest changes from the repository..."
    git pull origin main

    # Check if the pull was successful
    if [ $? -ne 0 ]; then
        echo "Failed to pull the latest changes. Exiting script."
        exit 1
    fi

    # Add changes only in the 'output' folder
    git add output/

    # Commit the changes
    COMMIT_MESSAGE="From Job: Update output folder after mistral-test-debugg session: $session temp: $temperature"
    # For mixtral or llama use: COMMIT_MESSAGE="Job: Update output folder after model: $model session: $session temp: $temperature"
    COMMIT_STATUS=$(git commit -m "$COMMIT_MESSAGE")

    # Check if the commit was successful
    if [[ $COMMIT_STATUS == *"nothing to commit"* ]]; then
        echo "No changes to commit."
    else
        echo "Changes committed. Pushing to repository..."
        # Push the changes
        git push origin main
        echo "Changes pushed successfully."
    fi
done
