import pytest
import namedtupleutils as namedtuple_utils
import collections as collections_module

def test_to_namedtuple_accepts_negative_float():
    """Call to_namedtuple with a negative float to ensure it handles the input without error."""
    negative_float = -476.66
    # Invoke the function under test; the test succeeds if no exception is raised.
    namedtuple_utils.to_namedtuple(negative_float)

def test_to_namedtuple_accepts_tuple_and_set():
    """Verify to_namedtuple can handle a tuple (float, set) and can also be called with a set."""
    value = -67.0
    # Create a set; repeating the same value has no effect because sets ignore duplicates.
    values_set = {value, value, value, value}
    tuple_input = (value, values_set)

    # Call to_namedtuple with a tuple and keep the returned value.
    result_namedtuple = namedtuple_utils.to_namedtuple(tuple_input)

    # Also call to_namedtuple with the set directly (return value intentionally ignored).
    namedtuple_utils.to_namedtuple(values_set)

def test_to_namedtuple_handles_dict_and_namedtuple_inputs_idempotently():
    """Call to_namedtuple on a dict (with repeated identical keys) and then on the result.

    The test constructs a dict literal with the same key repeated and calls to_namedtuple
    twice in succession to ensure the function can accept both dict and its own output.
    """
    key = "author"
    # Construct a dict literal with the same key repeated (the last occurrence is kept).
    mapping = {key: key, key: key, key: key}

    # First conversion: dict -> namedtuple-like object
    first_conversion = namedtuple_utils.to_namedtuple(mapping)

    # Second conversion: call to_namedtuple on the result returned above
    second_conversion = namedtuple_utils.to_namedtuple(first_conversion)

def test_to_namedtuple_accepts_raw_bytes_input():
    """Verify to_namedtuple accepts raw bytes input without raising an error."""
    raw_bytes = b"xs&,\x9b\xc2\xf1\x80\xb3y"
    # Call the function with the same bytes literal to ensure behavior is unchanged.
    namedtuple_utils.to_namedtuple(raw_bytes)

def test_to_namedtuple_with_empty_tuple_creates_namedtuple():
    """Call to_namedtuple with an empty tuple to ensure it handles that input."""
    # Arrange: empty tuple input
    empty_tuple = ()

    # Act: invoke the function under test; test passes if no exception is raised
    result = namedtuple_utils.to_namedtuple(empty_tuple)

    # Keep the result to mirror original behavior (no assertions required)
    _ = result

def test_to_namedtuple_with_ordered_dict_and_tuple():
    """Exercise to_namedtuple on OrderedDicts, nested namedtuples, and a tuple containing bytes.

    This ensures repeated conversions of the same OrderedDict and conversions from already-
    converted values behave the same way as the original autogenerated test.
    """
    # Start with an empty OrderedDict
    ordered = collections_module.OrderedDict()

    # Convert the OrderedDict to a namedtuple-like structure
    nt_from_ordered_1 = namedtuple_utils.to_namedtuple(ordered)

    # Convert the result again (conversion of an already-converted object)
    nt_from_nt = namedtuple_utils.to_namedtuple(nt_from_ordered_1)

    # Convert the original OrderedDict again (repeat conversion)
    nt_from_ordered_2 = namedtuple_utils.to_namedtuple(ordered)

    # Convert that second result once more
    nt_from_nt_2 = namedtuple_utils.to_namedtuple(nt_from_ordered_2)

    # A bytes value used as part of a tuple input to to_namedtuple
    bytes_blob = b"\xe2\xf8\xb9\x01\x8c\xa5\xed\xb1\x0e&rdHE"

    # Another conversion of the original OrderedDict
    nt_from_ordered_3 = namedtuple_utils.to_namedtuple(ordered)

    # Create a tuple combining a previously converted value and raw bytes
    combo = (nt_from_nt, bytes_blob)

    # Convert the tuple to a namedtuple-like structure
    nt_from_tuple = namedtuple_utils.to_namedtuple(combo)

    # Final conversion of the original OrderedDict (repeat)
    nt_final = namedtuple_utils.to_namedtuple(ordered)

def test_to_namedtuple_with_ordered_dict_using_non_identifier_key():
    """Exercise to_namedtuple with an OrderedDict created from a dict whose key is not a valid identifier.

    The test preserves original call ordering and behavior (including any exceptions that may be raised
    when using such keys as keyword arguments).
    """
    # A key string that contains characters not valid for Python identifiers.
    raw_key = "wm=-g\ry#\x0b#:*"

    # Construct a dict literal with duplicate entries for the same key (second entry overwrites the first).
    sample_dict = {raw_key: raw_key, raw_key: raw_key}

    # Attempt to build an OrderedDict by expanding the dict as keyword arguments.
    # (This mirrors the original test's behavior and may raise a TypeError because the key is not a valid identifier.)
    ordered_dict = collections_module.OrderedDict(**sample_dict)

    # Convert the OrderedDict to a namedtuple using the utility under test.
    nt = namedtuple_utils.to_namedtuple(ordered_dict)

    # Prepare a single-element list containing None and pass it positionally to OrderedDict,
    # matching the original invocation order and behavior.
    none_value = None
    single_item_list = [none_value]
    collections_module.OrderedDict(*single_item_list)

def test_to_namedtuple_handles_list_with_empty_list_and_none():
    """Call to_namedtuple on a list containing an empty list, then on None.

    Verifies that nested empty-list structures are accepted and that None can be passed
    without raising an exception.
    """
    # Prepare an empty inner list and a container list holding it
    empty_inner_list = []
    container_with_inner = [empty_inner_list]

    # First call: convert the container list to a namedtuple-like structure
    result = namedtuple_utils.to_namedtuple(container_with_inner)

    # Second call: ensure calling with None is allowed (no exception expected)
    none_value = None
    namedtuple_utils.to_namedtuple(none_value)

def test_to_namedtuple_with_various_input_shapes():
    """Exercise to_namedtuple with mappings, tuples, namedtuple instances and booleans.

    This test passes a fairly large documentation string as a repeated dict key/value,
    then converts that mapping to a namedtuple, wraps results in tuples and dicts,
    and calls to_namedtuple repeatedly to ensure it handles these different input
    shapes consistently (no assertions are performed; we preserve original call sequence).
    """
    # A long documentation string used as both key and value (repeated intentionally).
    long_docstring = (
        "Normalize a given path.\n\n    The given ``path`` will be normalized in the following process.\n\n    #. :obj:`bytes` will be converted to a :obj:`str` using the encoding\n       given by :obj:`getfilesystemencoding() <sys.getfilesystemencoding>`.\n    #. :obj:`PosixPath <pathlib.PosixPath>` and\n       :obj:`WindowsPath <pathlib.WindowsPath>` will be converted\n       to a :obj:`str` using the :obj:`as_posix() <pathlib.PurePath.as_posix>`\n       method.\n    #. An initial component of ``~`` will be replaced by that user’s\n       home directory.\n    #. Any environment variables will be expanded.\n    #. Non absolute paths will have the current working directory from\n       :obj:`os.getcwd() <os.cwd>`prepended.  If needed, use\n       :obj:`os.chdir() <os.chdir>` to change the current working directory\n       before calling this function.\n    #. Redundant separators and up-level references will be normalized, so\n       that ``A//B``, ``A/B/``, ``A/./B`` and ``A/foo/../B`` all become\n       ``A/B``.\n\n    Args:\n        path (:obj:`str`, :obj:`bytes` or :obj:`Path <pathlib.Path>`):\n            The path to be normalized.\n\n    :rtype:\n        :obj:`Path <pathlib.Path>`\n\n        * :obj:`PosixPath <pathlib.PosixPath>` or\n          :obj:`WindowsPath <pathlib.WindowsPath>` depending on the system.\n\n        .. Note:: :obj:`Path <pathlib.Path>` objects are immutable. Therefore,\n           any given ``path`` of type :obj:`Path <pathlib.Path>` will not be\n           the same object returned.\n\n    Example:\n\n        >>> from flutils.pathutils import normalize_path\n        >>> normalize_path('~/tmp/foo/../bar')\n        PosixPath('/home/test_user/tmp/bar')\n\n    "
    )

    # Create a mapping that uses the long docstring as key and value (repeated entries
    # are intentional to match the original test's literal).
    repeated_doc_mapping = {
        long_docstring: long_docstring,
        long_docstring: long_docstring,
        long_docstring: long_docstring,
    }

    # Convert the mapping to a namedtuple-like structure.
    namedtuple_a = namedtuple_utils.to_namedtuple(repeated_doc_mapping)

    # A boolean value used as a dict key later.
    false_flag = False

    # Convert the same mapping again (preserve original call sequence).
    namedtuple_b = namedtuple_utils.to_namedtuple(repeated_doc_mapping)

    # Wrap the previously obtained namedtuple in a single-element tuple.
    single_element_tuple = (namedtuple_b,)

    # Convert that tuple to a namedtuple-like structure.
    namedtuple_c = namedtuple_utils.to_namedtuple(single_element_tuple)

    # Build a mapping whose keys are a namedtuple and a boolean, mapping both to namedtuple_b.
    mixed_mapping = {namedtuple_c: namedtuple_b, false_flag: namedtuple_b}

    # Convert that mixed mapping to a namedtuple-like structure.
    namedtuple_d = namedtuple_utils.to_namedtuple(mixed_mapping)

    # Convert the resulting namedtuple-like object again.
    namedtuple_e = namedtuple_utils.to_namedtuple(namedtuple_d)

    # Another boolean (False) passed to to_namedtuple as in the original.
    another_false = False

    # Convert the earlier namedtuple-like object once more.
    namedtuple_f = namedtuple_utils.to_namedtuple(namedtuple_d)

    # Final call with a boolean value (original test makes this call without assertions).
    namedtuple_utils.to_namedtuple(another_false)

def test_to_namedtuple_handles_bytes_key_and_value():
    """Call to_namedtuple with a dict whose key and value are identical bytes objects."""
    # bytes value used both as key and value
    sample_bytes = b"F\xdb\xfdf\x8a\xe4\n\xa2\x1d[\xdc*\xa3\xba\xf6s}"
    input_dict = {sample_bytes: sample_bytes}
    # Invoke the function under test; the test passes if no exception is raised.
    namedtuple_utils.to_namedtuple(input_dict)

