import pytest

# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming_timer as timer

def test_timer_error_can_be_instantiated() -> None:
    """Test that a TimerError instance can be created successfully."""
    timer_error = timer.TimerError()

def test_timer_can_be_started_after_context_manager():
    """Test that a Timer can be started after being used as a context manager."""
    # Create a timer instance
    timer_instance = timer.Timer()
    
    # Use timer as context manager (starts on enter, stops on exit)
    context_timer = timer_instance.__enter__()
    exit_result = timer_instance.__exit__(None, None, None)
    
    # Start the timer after context manager has exited
    start_result = context_timer.start()
    
    # Start the same timer again (should raise error if already running)
    timer_instance.start()

def test_timer_context_manager_enter_exit_protocol() -> None:
    """Test that Timer context manager properly implements __enter__ and __exit__ methods."""
    # Create a Timer instance
    timer_instance = timer.Timer()
    
    # Enter context manager (starts timing)
    entered_timer = timer_instance.__enter__()
    
    # Exit context manager (stops timing)
    exit_result = timer_instance.__exit__(None, None, None)

def test_timer_exit_without_context() -> None:
    """Test that Timer.__exit__() can be called without entering context."""
    float_arg = timer.FloatArg()  # Unused in test
    timer_error = timer.TimerError()  # Unused in test
    timer = timer.Timer()
    timer.__exit__()

def test_timer_with_none_logger_and_dict_operations() -> None:
    """Test Timer with logger=None alongside dictionary operations."""
    # Create timer with no logger
    none_logger = None
    timer_instance = timer.Timer(logger=none_logger)
    
    # Start the timer (returns None)
    start_result = timer_instance.start()
    
    # Perform unrelated dictionary operation
    empty_dict = {}
    none_key = None
    # Set dictionary as its own value with None as key
    setitem_result = empty_dict.__setitem__(none_key, empty_dict)
    
    # Call __enter__ on the None result (unusual but preserves original behavior)
    setitem_result.__enter__()

def test_timer_operations_with_context_and_float_arg() -> None:
    """Test Timer operations including context manager, equality comparison, and initialization with FloatArg objects."""
    
    # Create initial timer and enter context
    timer_a = timer.Timer()
    context_timer = timer_a.__enter__()
    
    # Prepare test values
    negative_int = -1092
    float_arg1 = timer.FloatArg()
    
    # Create timer with Timer instance as initial_text (unusual but testing edge case)
    timer_b = timer.Timer(initial_text=context_timer)
    float_arg2 = timer.FloatArg()
    
    # Test equality comparison between timer and integer
    equality_result = timer_a.__eq__(negative_int)
    
    # Stop the context timer and get elapsed time
    elapsed_time = context_timer.stop()
    
    # Create timer with FloatArg as text and equality result as initial_text
    timer_c = timer.Timer(text=float_arg1, initial_text=equality_result)
    
    # Get string representations
    repr_a = timer_a.__repr__()
    repr_c = timer_c.__repr__()
    
    # Start the third timer
    start_result = timer_c.start()

def test_timer_initialization_with_repr_as_initial_text() -> None:
    """Test Timer initialization using __repr__() output as initial_text parameter."""
    # Create main timer and enter context manager
    main_timer = timer.Timer()
    context_timer = main_timer.__enter__()
    
    comparison_value = -1092
    
    # Get string representation of timer to use as initial_text
    timer_repr = context_timer.__repr__()
    
    # Create FloatArg instances for text parameter
    text_arg = timer.FloatArg()
    
    # Create timer with __repr__() output as initial_text
    timer_with_repr_initial_text = timer.Timer(initial_text=timer_repr)
    
    another_text_arg = timer.FloatArg()
    
    # Compare timer with integer value (likely returns False)
    equality_result = main_timer.__eq__(comparison_value)
    
    # Stop the context manager timer
    elapsed_time = context_timer.stop()
    
    # Create timer with custom text and initial_text from __repr__()
    timer_with_custom_text_and_initial_text = timer.Timer(
        text=text_arg, 
        initial_text=timer_repr
    )
    
    # Get string representations of timers
    main_timer_repr = main_timer.__repr__()
    custom_timer_repr = timer_with_custom_text_and_initial_text.__repr__()
    
    # Start the custom timer
    timer_with_custom_text_and_initial_text.start()

def test_timer_none_logger_start_exit_dict_setitem_none_key_and_attr_error():
    """Test Timer start and exit followed by operations on None."""
    # Create Timer with None logger
    logger_none = None
    timer_instance = timer.Timer(logger=logger_none)
    
    # Start the timer
    start_result = timer_instance.start()
    
    # Create empty dictionary
    empty_dict = {}
    
    # Call __exit__ to stop the timer
    exit_result = timer_instance.__exit__()
    
    # Perform dictionary operation with None key
    none_key = None
    setitem_result = empty_dict.__setitem__(none_key, empty_dict)
    
    # Call __repr__ on the result (which is None)
    repr_result = setitem_result.__repr__()
    
    # Attempt to call start on None (will raise AttributeError)
    setitem_result.start()

def test_timer_start_with_unusual_parameters() -> None:
    """Test that Timer can be started with unusual parameters (Timer instances as strings and booleans as logger)."""
    # Create a timer and enter its context
    timer = timer.Timer()
    entered_timer = timer.__enter__()  # Returns the timer itself
    
    # Check equality of timer with itself
    is_equal = timer.__eq__(timer)
    
    # Exit the timer context
    exit_result = timer.__exit__()
    
    # Create timer with Timer instance as initial_text and boolean as logger
    timer_with_initial_text_and_logger = timer.Timer(
        initial_text=entered_timer, 
        logger=is_equal
    )
    
    # Create timer with Timer instance as name, another Timer as initial_text, and boolean as logger
    timer_with_name_initial_text_and_logger = timer.Timer(
        entered_timer, 
        initial_text=timer_with_initial_text_and_logger, 
        logger=is_equal
    )
    
    # Start the timer - should not crash with unusual parameters
    timer_with_name_initial_text_and_logger.start()

def test_timer_start_stop_context_and_copy() -> None:
    """Test that a Timer can be started, stopped, used as a context manager, and copied."""
    # Create a timer with initial text
    initial_text = "Timer started"
    timer = timer.Timer(initial_text)
    
    # Start and stop the timer
    start_result = timer.start()  # Returns None
    elapsed_time = timer.stop()
    
    # Use timer as context manager
    context_timer = timer.__enter__()
    
    # Create a copy of the timer
    timer.copy()

