#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-570 -p alvis
#SBATCH --gpus-per-node=A100fat:3 #
#SBATCH -t 06:00:00
#SBATCH -o jobs/out/A100fat3_job.log  

model=deepseek
temperatures=(0.1 0.2 0.5 0.7)

versions=(
    "mix"
    "mix-cleanup"
    "functions"
    "functions-cleanup"
    "summarize"
    "summarize-cleanup"
)

job=Job-sum_functions_v2
# Arrays to store sessions, test paths, and module paths
sessions=(
    "codetiming"
    "decorators"
    "namedtupleutils"
    "packages"
    "cmd"
)

test_paths=(
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/codetiming._timer/test_codetiming__timer.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.decorators/test_flutils_decorators.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.namedtupleutils/test_flutils_namedtupleutils.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.packages/test_flutils_packages.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.setuputils.cmd/test_flutils_setuputils_cmd.py"
)

module_paths=(
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/codetiming._timer/codetiming_timer.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.decorators/decorators.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.namedtupleutils/namedtupleutils.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.packages/packages.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/flutils.setuputils.cmd/cmd.py"
)

ml purge

# Loop through each configuration

for i in "${!sessions[@]}"; do
    session="${sessions[$i]}"
    test_path="${test_paths[$i]}"
    module_path="${module_paths[$i]}"
    
    for temperature in "${temperatures[@]}"; do
        for version in "${versions[@]}"; do
            echo "Running with session $session, temperature $temperature, version $version"
            # Running test
            apptainer exec /cephyr/NOBACKUP/groups/llm-readability/setup/llama-pytest.sif python -m src.main \
            -m $model -s $session -t $temperature -p $module_path -tp $test_path -j $job -v $version
            
            # PUSHING TO REPO
            
            # Define the path to the repository's root
            REPO_DIR="/cephyr/NOBACKUP/groups/llm-readability/readability"
            
            # Change to the repository directory
            cd $REPO_DIR
            
            # Check if the directory change was successful
            if [ $? -ne 0 ]; then
                echo "Failed to change directory to $REPO_DIR. Exiting script."
                exit 1
            fi
            
            # Pull the latest changes from the remote repository
            echo "Pulling the latest changes from the repository..."
            git pull origin main
            
            # Check if the pull was successful
            if [ $? -ne 0 ]; then
                echo "Failed to pull the latest changes. Exiting script."
                exit 1
            fi
            
            # Add changes only in the 'output' folder
            git add output/
            
            # Commit the changes
            COMMIT_MESSAGE="From Loop Job: Update output folder after model: $model session: $session temp: $temperature version: $version"
            COMMIT_STATUS=$(git commit -m "$COMMIT_MESSAGE")
            
            # Check if the commit was successful
            if [[ $COMMIT_STATUS == *"nothing to commit"* ]]; then
                echo "No changes to commit for temperature $temperature and version $version."
            else
                echo "Changes committed. Pushing to repository..."
                # Push the changes
                git push origin main
                echo "Changes pushed successfully for temperature $temperature and version $version."
            fi
        done
    done
done