#!/usr/bin/env bash
#SBATCH -A NAISS2024-22-570 -p alvis
#SBATCH --gpus-per-node=A100:4 # 
#SBATCH -t 15:00:00
#SBATCH -o jobs/out/A100_job_long.log  

model=deepseek
temperatures=(0.1 0.2 0.5 0.7)

versions=(
    "functions"
    "functions-cleanup"
    "summarize"
    "summarize-cleanup"
    "mix"           # take the longes time
    "mix-cleanup"   # take the longes timegit pu
)

job=Job-versions-2
# Arrays to store sessions, test paths, and module paths
sessions=(
    "stringVal"
    "httpie"
    "queue"
)

test_paths=(
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/string_utils_validation/test_string_utils_validation.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/httpie_sessions/test_httpie_sessions.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/queue_example/test_queue_example.py"
)

module_paths=(
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/string_utils_validation/validation.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/httpie_sessions/sessions.py /cephyr/NOBACKUP/groups/llm-readability/readability/data/httpie_sessions/dicts.py"
    "/cephyr/NOBACKUP/groups/llm-readability/readability/data/queue_example/queue_example.py"
)

ml purge

# Loop through each configuration

for i in "${!sessions[@]}"; do
    session="${sessions[$i]}"
    test_path="${test_paths[$i]}"
    module_path="${module_paths[$i]}"
    
    for version in "${versions[@]}"; do
        for temperature in "${temperatures[@]}"; do
            echo "Running with session $session, temperature $temperature, version $version"
            # Running test
            apptainer exec /cephyr/NOBACKUP/groups/llm-readability/setup/llama-pytest.sif python -m src.main \
            -m $model -s $session -t $temperature -p $module_path -tp $test_path -j $job -v $version
            
            # PUSHING TO REPO
            
            # Define the path to the repository's root
            REPO_DIR="/cephyr/NOBACKUP/groups/llm-readability/readability"
            
            # Change to the repository directory
            cd $REPO_DIR
            
            # Check if the directory change was successful
            if [ $? -ne 0 ]; then
                echo "Failed to change directory to $REPO_DIR. Exiting script."
                exit 1
            fi
            
            # Pull the latest changes from the remote repository
            echo "Pulling the latest changes from the repository..."
            git pull origin main
            
            # Check if the pull was successful
            if [ $? -ne 0 ]; then
                echo "Failed to pull the latest changes. Exiting script."
                exit 1
            fi
            
            # Add changes only in the 'output' folder
            git add output/
            
            # Commit the changes
            COMMIT_MESSAGE="From Loop Job: Update output folder after model: $model session: $session temp: $temperature version: $version"
            COMMIT_STATUS=$(git commit -m "$COMMIT_MESSAGE")
            
            # Check if the commit was successful
            if [[ $COMMIT_STATUS == *"nothing to commit"* ]]; then
                echo "No changes to commit for temperature $temperature and version $version."
            else
                echo "Changes committed. Pushing to repository..."
                # Push the changes
                git push origin main
                echo "Changes pushed successfully for temperature $temperature and version $version."
            fi
        done
    done
done